global:
  labels:
    team: indexers
    severity: noncritical
  annotations:
    figment.io/github_repository: github.com/figment-networks/filecoin-indexer
  env:
    DATABASE_DSN:
      secretsManagerKeyRef:
        key: prod/indexers/filecoin-indexer
        property: database_dsn
    RPC_ENDPOINT: 51.222.104.211 # dh--filecoin-node--4
    ROLLBAR_ENV: prod
    ROLLBAR_TOKEN:
      secretsManagerKeyRef:
        key: prod/indexers/common
        property: rollbar_token

#jobs:
#  filecoin-indexer-migrations:
#    annotations:
#      helm.sh/hook: pre-install,pre-upgrade
#    pod:
#      containers:
#        filecoin-indexer-migration:
#          command:
#            - /app/bin/filecoin-indexer
#            - -cmd=migrate
#          resources:
#            requests:
#              memory: 200Mi
#              cpu: 500m
#            limits:
#              memory: 200Mi

deployments:
  filecoin-indexer-fetcher-manager:
    service:
      ports:
        http:
          port: 7000
          targetPort: 7000
          protocol: TCP
    replicas: 1
    pod:
      containers:
        filecoin-indexer-fetcher-manager:
          command:
            - /app/bin/filecoin-indexer
            - -cmd=fetcher
            - -mode=worker
          env:
            INITIAL_HEIGHT: 0
            BATCH_SIZE: 100
            WORKERS: filecoin-indexer-fetcher-worker-0
          livenessProbe:
            disabled: true
          readinessProbe:
            disabled: true
          resources:
            requests:
              memory: 200Mi
              cpu: 500m
            limits:
              memory: 200Mi

  filecoin-indexer-fetcher-worker-0:
    service:
      ports:
        http:
          port: 7000
          targetPort: 7000
          protocol: TCP
    replicas: 1
    pod:
      containers:
        filecoin-indexer-fetcher-worker:
          command:
            - /app/bin/filecoin-indexer
            - -cmd=fetcher
            - -mode=fetcher
          env:
            RPC_TIMEOUT: 1m
          livenessProbe:
            disabled: true
          readinessProbe:
            disabled: true
          resources:
            requests:
              memory: 200Mi
              cpu: 500m
            limits:
              memory: 200Mi

  filecoin-indexer-indexer:
    service:
      ports:
        http:
          port: 8080
          targetPort: 8080
          protocol: TCP
    replicas: 1
    pod:
      containers:
        filecoin-indexer-indexer:
          command:
            - /app/bin/filecoin-indexer
            - -cmd=indexer
          env:
            RPC_TIMEOUT: 1m
            INITIAL_HEIGHT: 0
            REDIS_URL: filecoin-indexer-redis:6379
            BATCH_SIZE: 100
          livenessProbe:
            disabled: true
          readinessProbe:
            disabled: true
          resources:
            requests:
              memory: 200Mi
              cpu: 500m
            limits:
              memory: 200Mi

  filecoin-indexer-server:
    service:
      ports:
        http:
          port: 8080
          targetPort: 8080
          protocol: TCP
    replicas: 1
    pod:
      containers:
        filecoin-indexer:
          command:
            - /app/bin/filecoin-indexer
            - -cmd=server
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
          resources:
            requests:
              memory: 200Mi
              cpu: 500m
            limits:
              memory: 200Mi


  filecoin-indexer-redis:
    service:
      ports:
        redis:
          port: 6379
          targetPort: 6379
          protocol: TCP
    replicas: 1
    pod:
      containers:
        redis:
          image: redis:6.2.3
          livenessProbe:
            tcpSocket:
              port: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
          resources:
            requests:
              memory: 4Gi
              cpu: 100m
            limits:
              memory: 4Gi



